--Category
INSERT INTO Category(Description) VALUES('Chinese')
INSERT INTO Category(Description) VALUES('Indian')
INSERT INTO Category(Description) VALUES('Thai')
INSERT INTO Category(Description) VALUES('Homemade')
INSERT INTO Category(Description) VALUES('Spicy')
INSERT INTO Category(Description) VALUES('Mexican')
INSERT INTO Category(Description) VALUES('Fast-food')

--Unit of measure
INSERT INTO Unit_Of_Measure(UOM) VALUES('tablespoon')
INSERT INTO Unit_Of_Measure(UOM) VALUES('tablespoons')
INSERT INTO Unit_Of_Measure(UOM) VALUES('teaspoon')
INSERT INTO Unit_Of_Measure(UOM) VALUES('teaspoons')
INSERT INTO Unit_Of_Measure(UOM) VALUES('milligram')
INSERT INTO Unit_Of_Measure(UOM) VALUES('milligrams')
INSERT INTO Unit_Of_Measure(UOM) VALUES('millilitre')
INSERT INTO Unit_Of_Measure(UOM) VALUES('millilitres')
INSERT INTO Unit_Of_Measure(UOM) VALUES ('dash')
INSERT INTO Unit_Of_Measure(UOM) VALUES ('whole')
INSERT INTO Unit_Of_Measure(UOM) VALUES('each')
INSERT INTO Unit_Of_Measure(UOM) VALUES('cups')
INSERT INTO Unit_Of_Measure(UOM) VALUES('pint')
